version: '3.4'

services: 
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "UseInMemoryDatabase=false"    
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/csharpexercise.pfx"
      - "DB_CONNECTION_STRING=host=postgres_image;port=5432;database=CSharp_Exercise;username=exercise_user;password=exercisepwd"
    volumes:
      - ./https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres_image
    restart: on-failure

  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=exercise_user
      - POSTGRES_PASSWORD=exercisepwd
      - POSTGRES_DB=CSharp_Exercise
    volumes:
      - ./dbscripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      

